version: '2'
services:
    wakecup-app:
        image: wakecup
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://wakecup-postgresql:5432/WakeCup
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    wakecup-postgresql:
        extends:
            file: postgresql.yml
            service: wakecup-postgresql
